
---
  title: "Andrés Talavera"
---

Bachiller en Ciencias Económicas de la Universidad Nacional Federico Villarreal, perteneciente al décimo superior, con
experiencia en la construcción y monitoreo de indicadores socioeconómicos. Manejo avanzado de programas para el análisis estadístico o econométrico: _Stata, R, Python, Tableau, Power Bi, KoboCollect_, entre otros. Con conocimientos en la redacción de informes y estudios. Predisposición de desarrollo profesional en áreas de investigación y análisis
económico.

### Principales servicios ### 

**Enseñanza**\

-  Construcción y análisis de indicadores socioeconómicos de empleo, educación, ingresos, gastos de los hogares, pobreza, desigualdad, salud, vivienda, empresariales, indicadores delictivos, entre otros, usando bases de datos de acceso público del Instituto Nacional de Estadísticas e Informática (INEI).
-  Visualización animada e interactiva con _Power Bi_, _Tableau_, _Affter Efects_ y otros. 
-  Econometría aplicada y ciencia de datos.
-  Uso de _R_, _Stata_ y _Python_ con microdatos abiertos.

**Talleres y ponencias ** 

  - Gráficas animadas e interactivas con Stata y R. 
  - Encuesta Nacional de hogares con Stata y R.  
  - Encuestas permanentes de empleo con Stata , R o Power Bi.
  - Construcción de indicadores del Censo Nacional Agropecuario (Cenagro)
  - Construcción de indicadores del Censo Nacional de Comisarías 

**Servicios de información e investigación** 

  ***Análisis socioeconómico con manejo de base de datos***
  
  - Elaboración de modelos econométricos de tipo regresión lineal, logísticos, probit, de variable dependiente limitada, Oaxaaca Blinder, regresión por cuantiles, modelos de duración o supervivencia, de panel, diferencias en diferencias, _propensity score matching (PSM)_, regresión discontínua y variables instrumentales.
  - Elaboración de pronósticos usando modelos de tipo árbol de decisión. 
  
  ***Trabajos de consistencia de encuestas o censos, tales como:***
  
  - Elaboración de reglas lógicas y flujos de consistencia. 
  - Elaboración de sintaxis
  - Elaboración de reportes de calidad y monitoreo 
  - Elaboración de sintaxis de indicadores
 
  ***Encuestas de opinión a nivel local, tales como:***
  
  - Percepción de la opinión pública sobre los problemas locales, regionales o            nacionales. 
  - Encuestas de opinión a empresas privadas para conocer el comportamiento de la         actividad empresarial
  - Encuestas de carácter social, demográfico, cultural, de salud, etc. 

### Curriculum Vitae ### 

Mi CV está actualizado [aquí](TalaveraCV.pdf). Si quieres saber cómo lo hice, puedes ver [una versión del código en Github.](https://github.com/atalaveracuya/CV) 

### Contáctame ### 
Comuníquese conmigo electrónicamente:

[E-mail](mailto:atalaveracuya@gmail.com) 
[Twitter](https://twitter.com/atalaveracuya)
[Linkedin](https://www.linkedin.com/in/atalaveracuya/) [GitHub](https://github.com/atalaveracuya/)


<footer>
  Copyright © 2023 Andrés Talavera Cuya. Todos los derechos reservados.
</footer>