
---
title: "Reportes"
output: 
 flexdashboard::flex_dashboard
 # orientation: rows
---

```{r configuracion, include=FALSE}

### configuraciones iniciales ####

rm(list=ls())


# Definicion del directorio de trabajo 

# Verificacion del directorio de trabajo
getwd()

library(flexdashboard)
library(dygraphs)
library(readxl)
library(ggplot2)
library(tidyverse)

# help("readxl")
# IPCpc     "Inflación"
# IPCepc    "IPC Alimentos y energía"
# IPC_sepc  "IPC Sin alimentos y energía"
# IPC_ABpc  "IPC Alimentos y bebidas"

inf_data <- readxl::read_excel("E:/ANDRES/Documents/Seriesdetiempo/Inflacion.xlsx", col_type=c("date","numeric","numeric","numeric","numeric"))
colnames(inf_data) <-c("fecha","inf","inf_alim_ener","inf_alim_beb","inf_salimener")

```



### Inflación Total

```{r selector, title, label, echo=FALSE}
library(dygraphs)
inf_total <- ts(inf_data$inf,frequency=12,start = c(2005,1))
dygraph(inf_total, main='INFLACION <br> <small>(Variación porcentual últimos 12 meses)</small>') %>% 
 dySeries("V1", label="Perú Inflación", color='blue') %>% 
 dyAxis("y", label="Variación porcentual últimos 12 meses") %>% 
 dyOptions(axisLineWidth = 0.5,
           fillGraph = TRUE,
           fillAlpha =0.1,
           drawGrid = FALSE) %>% 
dyLegend(show= "follow") %>% 
dyRangeSelector(height = 19)  

```


### Inflación por rubros (Var% 12 meses)
```{r multiple, echo=FALSE}

library(dygraphs)
inf <- ts(inf_data[,-1],frequency=12,start = c(2005,1))
dygraphs::dygraph(inf) %>% 
  dyAxis("y", label="Variación porcentual últimos 12 meses") %>% 
 dyOptions(axisLineWidth = 0.5,
           fillGraph = TRUE,
           fillAlpha =0.1,
           drawGrid = FALSE) %>% 
dyLegend(show= "follow") %>% 
  dySeries("inf",label="Inflación",color='blue') %>% 
  dySeries("inf_alim_ener",label="Alim. y Ener.",color='orange') %>%
  dySeries("inf_salimener",label="Sin Alim. y Ener.",color='green') %>% 
  dySeries("inf_alim_beb",label="Alim. y Beb.",color='red') 
```
> Nota: BCRP. Elaboración propia.


### Inflación y eventos importantes
```{r event, echo=FALSE}
library(dygraphs)
library(dplyr)
inf_data2=subset(inf_data,select = -c(inf_alim_ener,inf_salimener))
inf <- ts(inf_data2[,-1],frequency=12,start = c(2005,1))
  dygraph(inf, main="Inflación") %>% 
  dyAxis("y", label="Variación porcentual últimos 12 meses") %>% 
 dyOptions(axisLineWidth = 0.5,
           fillGraph = TRUE,
           fillAlpha =0.1,
           drawGrid = FALSE) %>% 
dyLegend(show= "follow") %>% 
  dySeries("inf",label="Inflación",color='blue') %>% 
  dySeries("inf_alim_beb",label="Alim. y Beb.",color='red')  %>%
  dyEvent("2020-03-01", "COVID-19", labelLoc = "bottom") %>% 
  dyShading(from = "2008-01-01", to="2008-12-01") %>% 
  dyEvent("2008-05-01", "2008 Crisis Financiera", labelLoc = "bottom")  
```
> Nota: BCRP. Elaboración propia.

### Predicción

``` {r upper/lower, echo=FALSE}
library(seasonal)
library(fpp2)
library(dygraphs)
inf_total <- ts(inf_data$inf,frequency=12,start = c(2005,1))
hw <- HoltWinters(inf_total)
predicted <- predict(hw, n.ahead=12, prediction.interval = TRUE)
all <- cbind(inf_total,predicted)

dygraph(all, "Proyección holtWinters de Inflación") %>% 
  dySeries("inf_total", label="Actual") %>% 
  dySeries(c("predicted.lwr", "predicted.fit", "predicted.upr"), label="Predicted")

```
> Nota: El gráfico fue creado por el autor basándose en una estimación propia.



<footer>
  Copyright © 2023 Andrés Talavera Cuya.
</footer>